apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.app }}
  name: {{ .Values.service.app }}
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.app }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
