namespace:
  name: sandbox
 
service:
  app: techtrends
  port: 4111
  protocol: TCP
  targetport: 3111
  type: ClusterIP

image:
  repository: sayon1205/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

ports:
  containerPort: 3111
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"