namespace:
  name: prod
 
service:
  app: techtrends
  port: 7111
  protocol: TCP
  targetport: 3111
  type: ClusterIP

image:
  repository: sayon1205/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  ports:
  - containerPort: 3111
    protocol: TCP
  livenessProbe:
   httpGet:
     path: /healthz
     port: 3111
  readinessProbe:
   httpGet:
     path: /healthz
     port: 3111
  resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"